version: '3'

# Taskfile for Terraform Actions GCP Patching Prototype
# Automates common development and deployment tasks
# Install Task: https://taskfile.dev/installation/

vars:
  TERRAFORM_DIR: terraform
  TESTS_DIR: tests
  SCRIPTS_DIR: scripts

tasks:
  # ============================================================================
  # Setup Tasks
  # ============================================================================
  
  setup:
    desc: "Complete setup - bootstrap GCP, configure Vault, and initialize Terraform"
    cmds:
      - task: bootstrap-gcp
      - task: setup-vault
      - task: tf-init

  bootstrap-gcp:
    desc: "Run GCP bootstrap script (one-time setup)"
    dir: "{{.SCRIPTS_DIR}}"
    cmds:
      - chmod +x bootstrap-gcp.sh
      - ./bootstrap-gcp.sh
    preconditions:
      - sh: command -v gcloud
        msg: "gcloud CLI not found. Install from https://cloud.google.com/sdk/docs/install"

  setup-vault:
    desc: "Interactive Vault setup - store GCP, AAP, and SSH credentials"
    cmds:
      - echo "=== Vault Setup ==="
      - echo "Checking Vault connectivity..."
      - vault status
      - echo ""
      - echo "Storing credentials in Vault..."
      - echo "1. GCP Service Account Key"
      - echo "2. AAP API Token"
      - echo "3. SSH Keys"
      - echo ""
      - echo "Run these commands manually:"
      - echo "  vault kv put secret/gcp/service-account key=@/path/to/sa-key.json project_id=PROJECT_ID"
      - echo "  vault kv put secret/aap/api-token token=YOUR_AAP_TOKEN"
      - echo "  vault kv put secret/ssh/ubuntu-key private_key=@~/.ssh/key public_key=@~/.ssh/key.pub"
    preconditions:
      - sh: command -v vault
        msg: "Vault CLI not found. Install from https://www.vaultproject.io/downloads"

  # ============================================================================
  # Terraform Tasks
  # ============================================================================

  tf-init:
    desc: "Initialize Terraform"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - terraform init

  tf-validate:
    desc: "Validate Terraform configuration"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - terraform validate
      - terraform fmt -check -recursive

  tf-fmt:
    desc: "Format Terraform files"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - terraform fmt -recursive

  tf-plan:
    desc: "Run Terraform plan"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - terraform plan

  tf-apply:
    desc: "Apply Terraform configuration (via HCP Terraform)"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - echo "⚠️  This workspace is connected to VCS"
      - echo "To apply changes:"
      - echo "1. Commit and push your changes: git add . && git commit -m 'message' && git push"
      - echo "2. Go to HCP Terraform: https://app.terraform.io/app/rahul-tfc/workspaces/tf-actions-aap-gcp"
      - echo "3. Review the auto-triggered plan"
      - echo "4. Click 'Confirm & Apply'"

  tf-destroy:
    desc: "Destroy Terraform-managed infrastructure"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - echo "⚠️  WARNING: This will destroy all infrastructure!"
      - echo "To destroy via HCP Terraform:"
      - echo "1. Go to: https://app.terraform.io/app/rahul-tfc/workspaces/tf-actions-aap-gcp/settings/destruction-and-deletion"
      - echo "2. Queue destroy plan"
      - echo "3. Confirm destruction"
    interactive: true

  tf-clean:
    desc: "Clean Terraform temporary files"
    dir: "{{.TERRAFORM_DIR}}"
    cmds:
      - rm -rf .terraform .terraform.lock.hcl
      - echo "✓ Terraform temporary files cleaned"

  # ============================================================================
  # Testing Tasks
  # ============================================================================

  test:
    desc: "Run all tests"
    cmds:
      - task: test-terraform
      - task: test-ansible
      - task: test-python

  test-terraform:
    desc: "Validate Terraform configuration"
    dir: "{{.TESTS_DIR}}"
    cmds:
      - chmod +x validate_terraform.sh
      - ./validate_terraform.sh

  test-ansible:
    desc: "Validate Ansible playbooks"
    dir: "{{.TESTS_DIR}}"
    cmds:
      - chmod +x validate_ansible.sh
      - ./validate_ansible.sh

  test-python:
    desc: "Run Python property-based tests"
    dir: "{{.TESTS_DIR}}"
    cmds:
      - |
        if [ ! -d "venv" ]; then
          echo "Creating Python virtual environment..."
          python3 -m venv venv
          ./venv/bin/pip install -r requirements.txt
        fi
      - ./venv/bin/pytest -v
    preconditions:
      - sh: command -v python3
        msg: "Python 3 not found"

  test-clean:
    desc: "Clean test artifacts"
    dir: "{{.TESTS_DIR}}"
    cmds:
      - rm -rf __pycache__ .pytest_cache .hypothesis venv
      - echo "✓ Test artifacts cleaned"

  # ============================================================================
  # Git Tasks
  # ============================================================================

  git-status:
    desc: "Check git status and show what will be committed"
    cmds:
      - git status
      - echo ""
      - echo "Files to be committed:"
      - git diff --name-only --cached

  git-commit:
    desc: "Commit changes with automated GCP setup"
    cmds:
      - task: clean
      - task: tf-fmt
      - git add .
      - git commit -m "feat: Add automated GCP setup with Vault integration"
      - echo ""
      - echo "✓ Changes committed"
      - echo "Run 'task git-push' to push to remote"

  git-push:
    desc: "Push changes to remote repository"
    cmds:
      - git push origin main
      - echo ""
      - echo "✓ Changes pushed to remote"
      - echo "HCP Terraform will auto-trigger a plan"
      - echo "Monitor at: https://app.terraform.io/app/rahul-tfc/workspaces/tf-actions-aap-gcp"

  # ============================================================================
  # Cleanup Tasks
  # ============================================================================

  clean:
    desc: "Clean all temporary files and artifacts"
    cmds:
      - task: tf-clean
      - task: test-clean
      - echo "✓ All temporary files cleaned"

  # ============================================================================
  # Documentation Tasks
  # ============================================================================

  docs:
    desc: "Open documentation in browser"
    cmds:
      - echo "Documentation:"
      - echo "  README.md - Project overview"
      - echo "  docs/AUTOMATED_SETUP.md - Automated setup guide"
      - echo "  docs/GCP_SETUP.md - GCP configuration"
      - echo "  docs/AAP_SETUP.md - AAP configuration"
      - echo "  docs/DEMO_WORKFLOW.md - Demo walkthrough"

  # ============================================================================
  # Deployment Tasks
  # ============================================================================

  deploy:
    desc: "Full deployment workflow"
    cmds:
      - echo "=== Terraform Actions GCP Patching Deployment ==="
      - echo ""
      - echo "Step 1: Validate configuration"
      - task: tf-validate
      - echo ""
      - echo "Step 2: Run tests"
      - task: test
      - echo ""
      - echo "Step 3: Commit and push"
      - task: git-commit
      - task: git-push
      - echo ""
      - echo "✓ Deployment initiated"
      - echo "Monitor progress in HCP Terraform"

  # ============================================================================
  # Utility Tasks
  # ============================================================================

  check-prereqs:
    desc: "Check if all prerequisites are installed"
    cmds:
      - echo "Checking prerequisites..."
      - echo -n "  gcloud: "
      - command -v gcloud && echo "✓" || echo "✗ (install from https://cloud.google.com/sdk/docs/install)"
      - echo -n "  terraform: "
      - command -v terraform && echo "✓" || echo "✗ (install from https://www.terraform.io/downloads)"
      - echo -n "  vault: "
      - command -v vault && echo "✓" || echo "✗ (install from https://www.vaultproject.io/downloads)"
      - echo -n "  python3: "
      - command -v python3 && echo "✓" || echo "✗"
      - echo -n "  git: "
      - command -v git && echo "✓" || echo "✗"

  help:
    desc: "Show available tasks"
    cmds:
      - task --list

  default:
    cmds:
      - task: help
